require_relative '../lib/movies_in_chicago_parks/cli.rb'
require_relative '../lib/movies_in_chicago_parks/showing.rb'
require_relative '../lib/movies_in_chicago_parks/park.rb'
require 'nokogiri'
require 'colorize'
